config/routes.rb
# Contributions
# Frank Evers: Addition of ports, boats, rooms, trips resources
# Andrew Storch: Addition of Devise :users, custom routes


Rails.application.routes.draw do
  resources :ports
  resources :reservations
  resources :boats
  resources :rooms
  resources :trips

  # use custom controller for registrations
  devise_for :users, :controllers => {registrations: 'user/registrations'}


  get 'home/index'
  root 'home#index'


  devise_scope :user do
    get 'users/sign_out', to: 'devise/sessions#destroy'
    get 'users/:id/edit', to: 'user/registrations#edit_user'
  end

  get 'home/show', to: 'home#show_reservations'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/trip.rb
# Contributions
# Frank Evers: File creation
# Johan McGwire: Validation, Association

class Trip < ApplicationRecord
	has_many :reservations
	belongs_to :boat
	belongs_to :ArrPort, class_name: "Port"
	belongs_to :DeptPort, class_name: "Port"
	validates :DeptPort_id, presence: true
	validates :ArrPort_id, presence: true
	validates :DeptDate, presence: true
	validates :ArrDate, presence: true, date: {after: :DeptDate, message: "The Arrival Date must be after the Departure Date"}
	validates :boat_id, presence: true
	validates :description, presence: true
end

app/controllers/trips_controller.rb
# Contributions
# Frank Evers: Generated controller file
# Andrew Storch: Require authorization before_action
# Johan McGwire: View updating after model assosiations added

class TripsController < ApplicationController
  before_action :set_trip, only: [:show, :edit, :update, :destroy]
  before_action :require_authorization, :except => [:index]

  # GET /trips
  # GET /trips.json
  def index
    @trips = Trip.all
  end

  # GET /trips/1
  # GET /trips/1.json
  def show
    @boats = Boat.all
  end

  # GET /trips/new
  def new
    @trip = Trip.new
  end

  # GET /trips/1/edit
  def edit
    @boats = Boat.all
  end

  # POST /trips
  # POST /trips.json
  def create
    @trip = Trip.new(trip_params)

    respond_to do |format|
      if @trip.save
        format.html { redirect_to @trip, notice: 'Trip was successfully created.' }
        format.json { render :show, status: :created, location: @trip }
      else
        format.html { render :new }
        format.json { render json: @trip.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trips/1
  # PATCH/PUT /trips/1.json
  def update
    respond_to do |format|
      if @trip.update(trip_params)
        format.html { redirect_to @trip, notice: 'Trip was successfully updated.' }
        format.json { render :show, status: :ok, location: @trip }
      else
        format.html { render :edit }
        format.json { render json: @trip.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trips/1
  # DELETE /trips/1.json
  def destroy
    @trip.destroy
    respond_to do |format|
      format.html { redirect_to trips_url, notice: 'Trip was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_trip
      @trip = Trip.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def trip_params
      params.require(:trip).permit(:boat_id, :DeptDate, :ArrDate, :DeptPort_id, :ArrPort_id, :description)
    end
end

app/helpers/trips_helper.rb
module TripsHelper
end

app/views/trips/_form.html.erb
<%= form_with(model: trip, local: true) do |form| %>
  <% if trip.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(trip.errors.count, "error") %> prohibited this trip from being saved:</h2>

      <ul>
      <% trip.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :boat_id %>
    <%= form.text_field :boat_id, id: :trip_boat %>
  </div>

  <div class="field">
    <%= form.label :DeptDate %>
    <%= form.date_select :DeptDate, id: :trip_DeptDate %>
  </div>

  <div class="field">
    <%= form.label :ArrDate %>
    <%= form.date_select :ArrDate, id: :trip_ArrDate %>
  </div>

  <div class="field">
    <%= form.label :DeptPort_id %>
    <%= form.text_field :DeptPort_id, id: :trip_DeptPort %>
  </div>

  <div class="field">
    <%= form.label :ArrPort_id %>
    <%= form.text_field :ArrPort_id, id: :trip_ArrPort %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description, id: :trip_description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/trips/_ports.html.erb
<div class="container-fluid">
  <table class="table table-striped">
    <thead>
    <tr>
      <th>PortID</th>
      <th>PortName</th>
      <th>Location</th>
    </tr>
    </thead>
    <tbody>
    <% @ports.each do |port| %>
    <tr>
      <td><%= port.id %></td>
      <td><%= port.name %></td>
      <td><%= trip.location.location %></td>
    </tr>
    <% end %>
    </tbody>
  </table>
</div>

app/views/trips/edit.html.erb
<h1>Editing Trip</h1>

<%= render 'form', trip: @trip %>

<%= link_to 'Show', @trip %> |
<%= link_to 'Back', trips_path %>

app/views/trips/index.html.erb
<head>
  <%= javascript_include_tag "jquery", "application" %>
    <%= javascript_include_tag "cycle" %>
    <%= javascript_include_tag "photoCycleJs", "data-turbolinks-track" => true  %>
</head>

<p id="notice"><%= notice %></p>

<h1 id = trips>Book A Trip With Us Today</h1>

<div id = "photoDiv" class= "carousel slide" data-ride="carousel">
  <div class= "carousel-inner" role = "listbox">
     <div class = "carousel-item active">
              
 <span id = "photoContainerA";>
  <%= image_tag("Alas1",width:500, height:250, :class => "rotating_Image" ) %>
  <%= image_tag("Alas2(night)",width:500, height:250, :class => "rotating_Image" ) %>
  <%= image_tag("alas3",width:500, height:250 , :class => "rotating_Image") %>
  </span>
  </span><span id = "photoContainerB";>
  <%= image_tag("boat1",width:500, height:250, :class => "rotating_Image" ) %>
  <%= image_tag("boat2",width:500, height:250, :class => "rotating_Image" ) %>
  <%= image_tag("boat3",width:500, height:250 , :class => "rotating_Image") %>
  </span><span id = "photoContainerC";>
  <%= image_tag("trop1",width:500, height:250, :class => "rotating_Image" ) %>
  <%= image_tag("trop2(night)",width:500, height:250, :class => "rotating_Image" ) %>
  <%= image_tag("trop2",width:500, height:250 , :class => "rotating_Image") %>
</span>
</div> </div> </div>


<span class="stretch"></span>
</div>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Boat ID</th>
      <th>Departure Date</th>
      <th>Arrival Date</th>
      <th>Departure Port</th>
      <th>Arrival Port</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @trips.each do |trip| %>
      <tr>
        <td><%= trip.boat.Name %></td>
        <td><%= trip.DeptDate %></td>
        <td><%= trip.ArrDate %></td>
        <td><%= trip.DeptPort.location %></td>
        <td><%= trip.ArrPort.location %></td>
        <td><%= trip.description %></td>
        <% if user_signed_in? && current_user.admin? %>
        <td><%= link_to 'Show', trip %></td>
        <td><%= link_to 'Edit', edit_trip_path(trip) %></td>
        <td><%= link_to 'Destroy', trip, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td><%= link_to 'Book!', new_reservation_path(:user_id => current_user.id, :trip_id => trip.id)%></td>
        <% else if user_signed_in? %>
        <td><%= link_to 'Book!', new_reservation_path(:user_id => current_user.id, :trip_id => trip.id)%></td>
        <% end %>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if user_signed_in? && current_user.admin? %>
<%= link_to 'New Trip', new_trip_path %>
<% end %>

app/views/trips/new.html.erb
<h1>New Trip</h1>

<%= render 'form', trip: @trip %>

<%= link_to 'Back', trips_path %>

app/views/trips/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Trip ID:</strong>
  <%= @trip.id %>
</p>

<p>
  <strong>Boat:</strong>
  <%= @trip.boat.Name %>
</p>

<p>
  <strong>Deptdate:</strong>
  <%= @trip.DeptDate %>
</p>

<p>
  <strong>Arrdate:</strong>
  <%= @trip.ArrDate %>
</p>

<p>
  <strong>Deptport:</strong>
  <%= @trip.DeptPort.location %>
</p>

<p>
  <strong>Arrport:</strong>
  <%= @trip.ArrPort.location %>
</p>

<p>
  <strong>Description:</strong>
  <%= @trip.description %>
</p>

<%= link_to 'Edit', edit_trip_path(@trip) %> |
<%= link_to 'Back', trips_path %>