config/routes.rb
# Contributions
# Frank Evers: Addition of ports, boats, rooms, trips resources
# Andrew Storch: Addition of Devise :users, custom routes


Rails.application.routes.draw do
  resources :ports
  resources :reservations
  resources :boats
  resources :rooms
  resources :trips

  # use custom controller for registrations
  devise_for :users, :controllers => {registrations: 'user/registrations'}


  get 'home/index'
  root 'home#index'


  devise_scope :user do
    get 'users/sign_out', to: 'devise/sessions#destroy'
    get 'users/:id/edit', to: 'user/registrations#edit_user'
  end

  get 'home/show', to: 'home#show_reservations'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/port.rb
# Contributions
# Frank Evers: File creation
# Johan McGwire: Validation, Association

class Port < ApplicationRecord
	has_many :trips
	validates :location, presence: true, uniqueness: true
	validates :country, presence: true
	validates :description, presence: true
end

app/controllers/ports_controller.rb
# Contributions
# Frank Evers: Generated controller file
# Andrew Storch: require_authorization
# Johan McGwire: View updating after model assosiations added


class PortsController < ApplicationController
  before_action :set_port, only: [:show, :edit, :update, :destroy]
  before_action :require_authorization

  # GET /ports
  # GET /ports.json
  def index
    @ports = Port.all
  end

  # GET /ports/1
  # GET /ports/1.json
  def show
  end

  # GET /ports/new
  def new
    @port = Port.new
  end

  # GET /ports/1/edit
  def edit
  end

  # POST /ports
  # POST /ports.json
  def create
    @port = Port.new(port_params)

    respond_to do |format|
      if @port.save
        format.html { redirect_to @port, notice: 'Port was successfully created.' }
        format.json { render :show, status: :created, location: @port }
      else
        format.html { render :new }
        format.json { render json: @port.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ports/1
  # PATCH/PUT /ports/1.json
  def update
    respond_to do |format|
      if @port.update(port_params)
        format.html { redirect_to @port, notice: 'Port was successfully updated.' }
        format.json { render :show, status: :ok, location: @port }
      else
        format.html { render :edit }
        format.json { render json: @port.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ports/1
  # DELETE /ports/1.json
  def destroy
    @port.destroy
    respond_to do |format|
      format.html { redirect_to ports_url, notice: 'Port was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_port
      @port = Port.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def port_params
      params.require(:port).permit(:location, :country, :description)
    end
end

app/helpers/ports_helper.rb
module PortsHelper
end

app/views/ports/_form.html.erb
<%= form_with(model: port, local: true) do |form| %>
  <% if port.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(port.errors.count, "error") %> prohibited this port from being saved:</h2>

      <ul>
      <% port.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :location %>
    <%= form.text_field :location, id: :port_location %>
  </div>

  <div class="field">
    <%= form.label :country %>
    <%= form.text_field :country, id: :port_country %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description, id: :port_description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/ports/edit.html.erb
<h1>Editing Port</h1>

<%= render 'form', port: @port %>

<%= link_to 'Show', @port %> |
<%= link_to 'Back', ports_path %>

app/views/ports/index.html.erb
<p id="notice"><%= notice %></p>
 <%= stylesheet_link_tag "photoCycle.css" %>
<h1>Ports</h1>

<table class= "table table-striped">
  <thead>
    <tr>
      <th>Port ID</th>
      <th>Location</th>
      <th>Country</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ports.each do |port| %>
      <tr>
        <td><%= port.id %></td>
        <td><%= port.location %></td>
        <td><%= port.country %></td>
        <td><%= port.description %></td>
        <% if user_signed_in? && current_user.admin? %>
          <td><%= link_to 'Show', port %></td>
          <td><%= link_to 'Edit', edit_port_path(port) %></td>
          <td><%= link_to 'Destroy', port, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if user_signed_in? && current_user.admin? %>
  <%= link_to 'New Port', new_port_path %>
<% end %>

app/views/ports/new.html.erb
<h1>New Port</h1>

<%= render 'form', port: @port %>

<%= link_to 'Back', ports_path %>

app/views/ports/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Port ID:</strong>
  <%= @port.id %>
</p>

<p>
  <strong>Location:</strong>
  <%= @port.location %>
</p>

<p>
  <strong>Country:</strong>
  <%= @port.country %>
</p>

<p>
  <strong>Description:</strong>
  <%= @port.description %>
</p>

<%= link_to 'Edit', edit_port_path(@port) %> |
<%= link_to 'Back', ports_path %>