config/routes.rb
# Contributions
# Frank Evers: Addition of ports, boats, rooms, trips resources
# Andrew Storch: Addition of Devise :users, custom routes


Rails.application.routes.draw do
  resources :ports
  resources :reservations
  resources :boats
  resources :rooms
  resources :trips

  # use custom controller for registrations
  devise_for :users, :controllers => {registrations: 'user/registrations'}


  get 'home/index'
  root 'home#index'


  devise_scope :user do
    get 'users/sign_out', to: 'devise/sessions#destroy'
    get 'users/:id/edit', to: 'user/registrations#edit_user'
  end

  get 'home/show', to: 'home#show_reservations'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/room.rb
# Contributions
# Frank Evers: File creation
# Johan McGwire: Validation, Association

class Room < ApplicationRecord
	has_many :reservations
	belongs_to :boat
	validates :boat_id, presence: true
  	validates :Name, presence: true, uniqueness: true
  	validates :Size, presence: true
  	validates :Price, presence: true
end

app/controllers/rooms_controller.rb
# Contributions
# Frank Evers: Generated controller file
# Andrew Storch: Added protection using before action
# Johan McGwire: View updating after model assosiations added


class RoomsController < ApplicationController
  before_action :set_room, only: [:show, :edit, :update, :destroy]
  before_action :require_authorization, except: [:index]
  # GET /rooms
  # GET /rooms.json
  def index
    @rooms = Room.all
  end

  # GET /rooms/1
  # GET /rooms/1.json
  def show
  end

  # GET /rooms/new
  def new
    @room = Room.new
  end

  # GET /rooms/1/edit
  def edit
  end

  # POST /rooms
  # POST /rooms.json
  def create
    @room = Room.new(room_params)

    respond_to do |format|
      if @room.save
        format.html { redirect_to @room, notice: 'Room was successfully created.' }
        format.json { render :show, status: :created, location: @room }
      else
        format.html { render :new }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rooms/1
  # PATCH/PUT /rooms/1.json
  def update
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to @room, notice: 'Room was successfully updated.' }
        format.json { render :show, status: :ok, location: @room }
      else
        format.html { render :edit }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1
  # DELETE /rooms/1.json
  def destroy
    @room.destroy
    respond_to do |format|
      format.html { redirect_to rooms_url, notice: 'Room was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room
      @room = Room.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def room_params
      params.require(:room).permit(:Name, :Size, :boat_id, :Price)
    end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/_form.html.erb
<%= form_with(model: room, local: true) do |form| %>
  <% if room.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(room.errors.count, "error") %> prohibited this room from being saved:</h2>

      <ul>
      <% room.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label "Room Name:" %>
    <%= form.text_field :Name, id: :room_Name %>
  </div>

  <div class="field">
    <%= form.label :Capacity %>
    <%= form.text_field :Size, id: :room_Size %>
  </div>

  <div class="field">
    <%= form.label :boat_id %>
    <%= form.text_field :boat_id, id: :room_ContainingBoat %>
  </div>

  <div class="field">
    <%= form.label :Price %>
    <%= form.text_field :Price, id: :room_Price %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/rooms/edit.html.erb
<h1>Editing Room</h1>

<%= render 'form', room: @room %>

<%= link_to 'Show', @room %> |
<%= link_to 'Back', rooms_path %>

app/views/rooms/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Rooms</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Room Id</th>
      <th>Boat</th>
      <th>Room Number</th>
      <th>Size</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rooms.each do |room| %>
      <tr>
        <td><%= room.id %></td>
        <td><%= room.boat.Name %></td>
        <td><%= room.Name %></td>
        <td><%= room.Size %></td>
        <td><%= room.Price %></td>
        <% if user_signed_in? && current_user.admin? %>
          <td><%= link_to 'Show', room %></td>
          <td><%= link_to 'Edit', edit_room_path(room) %></td>
          <td><%= link_to 'Destroy', room, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Room', new_room_path %>

app/views/rooms/new.html.erb
<h1>New Room</h1>

<%= render 'form', room: @room %>

<%= link_to 'Back', rooms_path %>

app/views/rooms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Room ID:</strong>
  <%= @room.id %>
</p>

<p>
  <strong>RoomName:</strong>
  <%= @room.Name %>
</p>

<p>
  <strong>Size:</strong>
  <%= @room.Size %>
</p>

<p>
  <strong>Containingboat:</strong>
  <%= @room.boat.Name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @room.Price %>
</p>

<%= link_to 'Edit', edit_room_path(@room) %> |
<%= link_to 'Back', rooms_path %>