config/routes.rb
# Contributions
# Frank Evers: Addition of ports, boats, rooms, trips resources
# Andrew Storch: Addition of Devise :users, custom routes


Rails.application.routes.draw do
  resources :ports
  resources :reservations
  resources :boats
  resources :rooms
  resources :trips

  # use custom controller for registrations
  devise_for :users, :controllers => {registrations: 'user/registrations'}


  get 'home/index'
  root 'home#index'


  devise_scope :user do
    get 'users/sign_out', to: 'devise/sessions#destroy'
    get 'users/:id/edit', to: 'user/registrations#edit_user'
  end

  get 'home/show', to: 'home#show_reservations'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/boat.rb
# Contributions
# Frank Evers: File creation
# Johan McGwire: Validation, Association

class Boat < ApplicationRecord
	has_many :trips
 	has_many :rooms
 	validates :Name, presence: true, uniqueness: true
 	validates :NumberOfRooms, presence: true
end

app/controllers/boats_controller.rb
# Contributions
# Frank Evers: creation of Boats scaffold
# Andrew Storch: protection via before_action
# Johan McGwire: View updating after model assosiations added


class BoatsController < ApplicationController
  before_action :set_boat, only: [:show, :edit, :update, :destroy]
  before_action :require_authorization

  # GET /boats
  # GET /boats.json
  def index
    @boats = Boat.all
  end

  # GET /boats/1
  # GET /boats/1.json
  def show
  end

  # GET /boats/new
  def new
    @boat = Boat.new
  end

  # GET /boats/1/edit
  def edit
  end

  # POST /boats
  # POST /boats.json
  def create
    @boat = Boat.new(boat_params)

    respond_to do |format|
      if @boat.save
        format.html { redirect_to @boat, notice: 'Boat was successfully created.' }
        format.json { render :show, status: :created, location: @boat }
      else
        format.html { render :new }
        format.json { render json: @boat.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /boats/1
  # PATCH/PUT /boats/1.json
  def update
    respond_to do |format|
      if @boat.update(boat_params)
        format.html { redirect_to @boat, notice: 'Boat was successfully updated.' }
        format.json { render :show, status: :ok, location: @boat }
      else
        format.html { render :edit }
        format.json { render json: @boat.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /boats/1
  # DELETE /boats/1.json
  def destroy
    @boat.destroy
    respond_to do |format|
      format.html { redirect_to boats_url, notice: 'Boat was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_boat
      @boat = Boat.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def boat_params
      params.require(:boat).permit(:Name, :NumberOfRooms)
    end
end

app/helpers/boats_helper.rb
module BoatsHelper
end

app/views/boats/_form.html.erb
<%= form_with(model: boat, local: true) do |form| %>
  <% if boat.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(boat.errors.count, "error") %> prohibited this boat from being saved:</h2>

      <ul>
      <% boat.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :Name %>
    <%= form.text_field :Name, id: :boat_Name %>
  </div>

  <div class="field">
    <%= form.label :NumberOfRooms %>
    <%= form.text_field :NumberOfRooms, id: :boat_NumberOfRooms %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/boats/edit.html.erb
<h1>Editing Boat</h1>

<%= render 'form', boat: @boat %>

<%= link_to 'Show', @boat %> |
<%= link_to 'Back', boats_path %>

app/views/boats/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Boats</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Boat Id</th>
      <th>Name</th>
      <th>Number Of Rooms</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @boats.each do |boat| %>
      <tr>
        <td><%= boat.id %></td>
        <td><%= boat.Name %></td>
        <td><%= boat.NumberOfRooms %></td>
        <td><%= link_to 'Show', boat %></td>
        <td><%= link_to 'Edit', edit_boat_path(boat) %></td>
        <td><%= link_to 'Destroy', boat, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if user_signed_in? && current_user.admin? %>
<%= link_to 'New Boat', new_boat_path %>
<%end%>

app/views/boats/new.html.erb
<h1>New Boat</h1>

<%= render 'form', boat: @boat %>

<%= link_to 'Back', boats_path %>

app/views/boats/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Boat ID:</strong>
  <%= @boat.id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @boat.Name %>
</p>

<p>
  <strong>Numberofrooms:</strong>
  <%= @boat.NumberOfRooms %>
</p>



<%= link_to 'Edit', edit_boat_path(@boat) %> |
<%= link_to 'Back', boats_path %>